Batch custom scopes activation
quarkiverse/quarkus-jberet pull request #123
Opened 2022-05-16 15:02 UTC by luca-bassoricci

- Fixes https://github.com/quarkiverse/quarkus-jberet/issues/122

Added job/step/partition scope management

I've added Quarkus specific implementation for batch scopes in runtime module and registered them in `JBeretProcessor`.
I marked PR as draft mainly because:

1. I'm not sure Quarkus specific implementations are implemented in the right way because they are reflection based
2. Tests are missing

2022-05-23 19:41 UTC, radcortez commented
@luca-bassoricci Thanks for the PR.

Maybe we can implement some of the changes in JBeret directly (change method visibilities), so we can use them here directly without requiring reflection. I had to do some of that work when we first wrote the extension. I'm sure @chengfang will help.

If this is a major blocker for you, I'm fine if we move with the reflection based approach while we do the work in JBeret, but we do need tests :)

Thanks!

2022-05-23 20:02 UTC, chengfang commented
@luca-bassoricci  please file [JBeret JIRA](https://issues.redhat.com/issues/?jql=project%20%3D%20JBERET%20ORDER%20BY%20key%20DESC) issues for changes needed from [JBeret](https://github.com/jberet/jsr352), and we'll evaluate if it's suitable to include it.

2022-05-25 07:20 UTC, luca-bassoricci commented
> @luca-bassoricci please file [JBeret JIRA](https://issues.redhat.com/issues/?jql=project%20%3D%20JBERET%20ORDER%20BY%20key%20DESC) issues for changes needed from [JBeret](https://github.com/jberet/jsr352), and we'll evaluate if it's suitable to include it.

JIRA issue: https://issues.redhat.com/browse/JBERET-561

2022-05-26 21:39 UTC, chengfang commented
@luca-bassoricci  @radcortez  all 3 ScopedContextImpl classes have a static `INSTANCE` field (though not public). Can you use them instead of accessing their constructor? If so, we can add a getInstance() public method.

2022-05-26 22:05 UTC, chengfang commented
After reading more about this PR, I'd like to suggest something slightly different:

Can `QuarkusJobScopedContextImpl` and the like extend jberet's `JobScopedContextImpl`?  This will avoid quite some method duplicatation, without the need to access the constructor.

Is the only purpose of accessing `getJobScopedBeans` is to use it in `destroy()` method? If so, the parent class in jberet can implement the `destroy()` method with the same logic accessing the jberet-private `getJobScopedBeans()`. So Quarkus side does not need to access `getJobScopedBeans()` at all.

Will the above work?

2022-05-27 08:51 UTC, luca-bassoricci commented
> all 3 ScopedContextImpl classes have a static INSTANCE field (though not public). Can you use them instead of accessing their constructor? If so, we can add a getInstance() public method in jberet ScopedContextImpl classes.

> After reading more about this PR, I'd like to suggest something slightly different:
> 
> Can `QuarkusJobScopedContextImpl` and the like extend jberet's `JobScopedContextImpl`? This will avoid quite some method duplicatation, without the need to access the constructor.

As my personal opinion I prefer to access private `INSTANCE` fields via a static `getInstance()`; for example using a new class just for Quarkus (eg `QuarkusCDIExtension`) where scopes `INSTANCE`s are exposed using the a public  `getXXXScopeInstance()`; this is because I prefer to use delegation over extension.

> 
> Is the only purpose of accessing `getJobScopedBeans` is to use it in `destroy()` method? If so, the parent class in jberet can implement the `destroy()` method with the same logic accessing the jberet-private `getJobScopedBeans()`. So Quarkus side does not need to access `getJobScopedBeans()` at all.
> 
> Will the above work?

Yep, for now the solely usage is that.
I have only some concerns about my implementation of [`AlterableContext#destroy([Contextual](https://docs.oracle.com/javaee/7/api/javax/enterprise/context/spi/Contextual.html)<?> contextual)`](https://docs.oracle.com/javaee/7/api/javax/enterprise/context/spi/AlterableContext.html#destroy-javax.enterprise.context.spi.Contextual-) but I opened a review on my PR to let @radcortez have a look and give his opinion about this problem.

2022-05-31 13:21 UTC, chengfang commented
Okay, based on the above discussion, here is my plan for jberet-side changes:
* add `public static getInstance()` method to jberet scoped context impl classes;
* add `public void destroy()` method to jberet scoped context impl classes, so quarkus-jberet classes can either inherit or delegate to it.
* constructor and `getScopedBeans()` methods in jberet will remain private (unchanged).

2022-06-02 18:46 UTC, chengfang commented
https://github.com/jberet/jsr352/pull/232 is the jberet PR. Please review and let me know if anything else is needed.

Note that a single `destroy(Contextual<?>)` method is added. This method destroys a specific bean, but if called with `null`, it will behave the same as what you would want in `destroy()` -- to destroy all beans.

Also note that the latest quarkus `InjectableContext` interface has changed: there is now a `destroy(ContextState)` method replacing `destroy(Contextual<?>)`.

2022-06-06 08:04 UTC, luca-bassoricci commented
> [jberet/jsr352#232](https://github.com/jberet/jsr352/pull/232) is the jberet PR. Please review and let me know if anything else is needed.
> 
> Note that a single `destroy(Contextual<?>)` method is added. This method destroys a specific bean, but if called with `null`, it will behave the same as what you would want in `destroy()` -- to destroy all beans.
> 
> Also note that the latest quarkus `InjectableContext` interface has changed: there is now a `destroy(ContextState)` method replacing `destroy(Contextual<?>)`.

I've seen your PR and LGTM, but I have also seen `InjectableContext` changes so I need more time to investigate.
I'll update you all ASAP.

2023-01-27 07:33 UTC, luca-bassoricci commented
@chengfang 

> > [jberet/jsr352#232](https://github.com/jberet/jsr352/pull/232) is the jberet PR. Please review and let me know if anything else is needed.
> > Note that a single `destroy(Contextual<?>)` method is added. This method destroys a specific bean, but if called with `null`, it will behave the same as what you would want in `destroy()` -- to destroy all beans.
> > Also note that the latest quarkus `InjectableContext` interface has changed: there is now a `destroy(ContextState)` method replacing `destroy(Contextual<?>)`.
> 
> I've seen your PR and LGTM, but I have also seen `InjectableContext` changes so I need more time to investigate. I'll update you all ASAP.

@chengfang 
I suppose you can merge your PR.

2023-12-05 15:45 UTC, chrisschauer commented
Any progress here? I stumbled over the same issue with JobScoped beans. 
Thanks

2023-12-05 18:37 UTC, radcortez commented
Unsure. This PR has been stale for some time. @luca-bassoricci do you intend to keep working on this? Thanks!

2023-12-06 06:52 UTC, luca-bassoricci commented
I'll be happy to work on it but on my (short) spare time because I am a bit busy at work, sorry.
I pinged cheofang times ago but without response.
Codebase on my branch is still with Quarkus 2.x, so I need to upgrade to latest Quarkus and JBeret.
May we drop support for Quarkus 2.x, WDYT @radcortez ?

2023-12-06 12:45 UTC, radcortez commented
> May we drop support for Quarkus 2.x, WDYT @radcortez ?

Sure.

2023-12-06 15:06 UTC, liweinan commented
I'll check this.

2023-12-07 09:18 UTC, luca-bassoricci commented
I have aligned with latest extension codebase and JBeret 2.2.0-SNAPSHOT (current main) where chengfang PR will be merged later
@radcortez build fails because jberet 2.2.0-SNAPSHOT dependency: IDK which is the right way to proceed in this case when using an external snapshot repository as dep.

2023-12-07 12:13 UTC, radcortez commented
One technique that I use is to add a step into the ci builder to clone and build locally the snapshot dependency until we have a stable release.

2023-12-14 11:21 UTC, luca-bassoricci commented
> > One technique that I use is to add a step into the ci builder to clone and build locally the snapshot dependency until we have a stable release.
> 
> That's fine. Done.

@radcortez I'm currently use the main branch of Jberet to build locally, but what about using chengfang:scope-impl-public-JBERET-561 instead? This should avoid @liweinan to merge the PR until we decide to remove the draft to this PR.
WDYT?

2023-12-14 16:56 UTC, liweinan commented on .github/workflows/build.yml
> +          repository: jberet/jsr352
@luca-bassoricci Maybe you can directly use cheng's fork repo here.

2023-12-14 16:57 UTC, liweinan commented on .github/workflows/build.yml
> +        run: mvn compile install --file jberet_jsr352-snapshot/pom.xml
@luca-bassoricci And then checkout this branch from his fork

2023-12-15 10:13 UTC, radcortez commented
> @radcortez I'm currently use the main branch of Jberet to build locally, but what about using chengfang:scope-impl-public-JBERET-561 instead? This should avoid @liweinan to merge the PR until we decide to remove the draft to this PR. WDYT?

Yes, it's fine.

2023-12-15 10:44 UTC, luca-bassoricci commented
@liweinan created a new branch based on jberet 2.x and I'm already using it; cheng's branch IMO can be dismissed because we don't support pre-jakarta code.
@liweinan no rush to merge your branch, we can use your branch until this PR is draft

2023-12-15 14:33 UTC, liweinan commented
@luca-bassoricci Cool! :-) I'll finish doing TCK tests today but I guess do the release need sometime, anyway I'll finish working on this before next weekend.

In addition, just to confirm that you don't need the PR for JBeret `1.4.x` right? If that's true I'll just do the release for `2.1.x`.

2023-12-15 15:21 UTC, luca-bassoricci commented
> In addition, just to confirm that you don't need the PR for JBeret `1.4.x` right? If that's true I'll just do the release for `2.1.x`.

Confirmed

 
> To be concise: If Quarkus side has no specific requirement, and if you can just use the [jberet/jsr352#432 (comment)](https://github.com/jberet/jsr352/pull/432#issuecomment-1857373023), I'll do a release `2.2.0.Final` from main branch, because branch `2.1` is for EAP8.

IDK if Quarkus has specific requirements, maybe @radcortez can answer.
As stated above I'm currently use your PR branch while in draft but if backport to 2.1 (https://github.com/jberet/jsr352/pull/432#issuecomment-1856172415)  we can decide to move to 2.1.x-stable as base anytime

2023-12-15 15:25 UTC, liweinan commented
@luca-bassoricci Thanks for the confirmation! Okay I'll do the `2.2.0.Final` once TCK tests are done, and if it needs to be back-ported into branch `2.1` in the future please let me know.

2023-12-17 18:29 UTC, liweinan commented
@luca-bassoricci I have released `2.2.0.Final` for use: https://github.com/jberet/jsr352/releases/tag/2.2.0.Final If there is any problem please let me know.

2023-12-20 16:00 UTC, luca-bassoricci commented
> 
> If this is a major blocker for you, I'm fine if we move with the reflection based approach while we do the work in JBeret, but we do need tests :)
> 

About tests:
My idea is to import JBeret tests from https://github.com/jberet/jsr352/tree/main/test-apps/cdiScopes and add them to integration-test module instead of create a new set of tests from scratch.
![jberet-scope-tests](https://github.com/quarkiverse/quarkus-jberet/assets/73338789/7b90e41c-6c54-4d8e-b9e2-1955ca2fc77a)


@radcortez WDYT?

2023-12-22 12:34 UTC, radcortez commented
> About tests: My idea is to import JBeret tests from https://github.com/jberet/jsr352/tree/main/test-apps/cdiScopes and add them to integration-test module instead of create a new set of tests from scratch. 
>
> @radcortez WDYT?

Sounds good.

2023-12-22 23:20 UTC, luca-bassoricci commented
Tests added.
I have used JBeret test artifacts, create alternative beans because JBeret's ones are not `@Dependent` and copied *IT tests.
commons project contains a base abstract test class useful to integrate with JBeret test classes.
Let me know

2024-01-10 08:50 UTC, luca-bassoricci commented
> Tests added. I have used JBeret test artifacts, create alternative beans because JBeret's ones are not `@Dependent` and copied *IT tests. `commons` project contains a base abstract test class useful to integrate with JBeret test classes. I had to add a reflection call [here](https://github.com/quarkiverse/quarkus-jberet/pull/123/files#diff-f004ce9e7a3d666465c079bb2ffd37e8f45c55477cee65934d745b50dde22091) but I don't think is a concern because it only a test and not runtime code. Let me know.

@radcortez any comment?

2024-01-10 17:02 UTC, radcortez commented
> @radcortez any comment?

Yes, it is fine. Thank you.

So, is this complete? Or are we still missing something?

2024-01-11 10:55 UTC, luca-bassoricci commented
From my POV all seems to be fine; for me a big concern was about the tests but after JBeret's tests passed I'm more confident.
I suppose draft status can be removed and PR merged.

2024-01-12 06:53 UTC, luca-bassoricci commented
> > @radcortez any comment?
> 
> Yes, it is fine. Thank you.
> 
> So, is this complete? Or are we still missing something?

From my POV all seems to be fine; for me a big concern was about the tests but after JBeret's tests passed I'm more confident.
I suppose draft status can be removed and PR merged.

2024-01-12 07:57 UTC, liweinan commented
btw JBeret `2.2.0.Final` has been merged into WildFly main branch: https://github.com/wildfly/wildfly/pull/17519#event-11463054652

2024-01-15 11:18 UTC, radcortez requested changes

2024-01-15 11:18 UTC, radcortez commented on core/deployment/src/main/java/io/quarkiverse/jberet/deployment/JBeretProcessor.java
> +    public void registerExtension(BuildProducer<FeatureBuildItem> feature,
It seems that in this class, there are a bunch of changes that are only code style changes and not related to the actual feature. Any chance we can revert these and keep only the relevant changes?

2024-01-16 10:22 UTC, radcortez approved these changes
Thank you for all the work. Really appreciate it :)

2024-01-16 10:23 UTC, merged